server:
  address: "localhost"
  port: 8080

spring.profiles.active: dev

# ===============================
# DATABASE
# ===============================

spring.datasource.driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url: jdbc:sqlserver://192.168.102.10\ibd_test:1433;encrypt=false;database=ibd_test
spring.datasource.url: jdbc:sqlserver://192.168.102.10\ibd_sec:1433;encrypt=false;database=ibd_sec
spring.datasource.username: sa
spring.datasource.password: hf,jnfflvbyf

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
